### ISSUE TITLE
API de BIP no funciona

### ISSUE THREAD

**Issue by heysoypaez** [juanbrujo/listado-apis-publicas-en-chile#39]
Hola, probe la API de BIP que mostraron con Node.js y no funciona.

Además, más que API es una libreria exclusiva de Node.js, si alguien quisiera usarla con Python o Php no podría, les recomiendo reemplazarla con esta que encontré y me sirvió: [http://bip-servicio.herokuapp.com/](http://bip-servicio.herokuapp.com/)

**Comment by heysoypaez** [comment]
Con no funciona me refiero a que me da este error:

````
Error: Esta tarjeta no se puede cargar
    at IncomingMessage.<anonymous> (/Users/usuario/Documents/dev/applications/js/node/bip/node_modules/bip/src/index.js:113:22)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
````

Cuando me consta que funciona porque la uso.

**Comment by cotelatorre** [comment]
¡Hola! Esta API me funcionó a mí https://xor.cl/api/red/, probé la librería de la bip y tampoco me funcionó.
¡Un saludo!

**Comment by juanbrujo** [comment]
link actualizado
